"undefined"==typeof this.dwr&&(this.dwr={});"undefined"==typeof dwr.util&&(dwr.util={});"undefined"==typeof this.DWRUtil&&(this.DWRUtil=dwr.util);dwr.util._escapeHtml=!0;dwr.util.setEscapeHtml=function(a){dwr.util._escapeHtml=a};dwr.util._shouldEscapeHtml=function(a){return a&&null!=a.escapeHtml?a.escapeHtml:dwr.util._escapeHtml};dwr.util.escapeHtml=function(a){return a.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")};
dwr.util.unescapeHtml=function(a){return a.replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">")};dwr.util.replaceXmlCharacters=function(a){a=a.replace("&","+");a=a.replace("<","\u2039");a=a.replace(">","\u203a");a=a.replace("'","\u2018");return a=a.replace('"',"\u201c")};dwr.util.containsXssRiskyCharacters=function(a){return-1!=a.indexOf("&")||-1!=a.indexOf("<")||-1!=a.indexOf(">")||-1!=a.indexOf("'")||-1!=a.indexOf('"')};
dwr.util.onReturn=function(a,b){a||(a=window.event);a&&a.keyCode&&13==a.keyCode&&b()};dwr.util.selectRange=function(a,b,c){a=dwr.util._getElementById(a,"selectRange()");if(null!=a){if(a.setSelectionRange)a.setSelectionRange(b,c);else if(a.createTextRange){var d=a.createTextRange();d.moveStart("character",b);d.moveEnd("character",c-a.value.length);d.select()}a.focus()}};
document.getElementById?dwr.util.byId=function(){for(var a=[],b=0;b<arguments.length;b++){var c=arguments[b];"string"==typeof c&&(c=document.getElementById(c));if(1==arguments.length)return c;a.push(c)}return a}:document.all&&(dwr.util.byId=function(){for(var a=[],b=0;b<arguments.length;b++){var c=arguments[b];"string"==typeof c&&(c=document.all[c]);if(1==arguments.length)return c;a.push(c)}return a});var $;$||($=dwr.util.byId);
dwr.util.toDescriptiveString=function(a,b,c){function d(a,b,c,e){var g="";try{if("string"==typeof a){0==b&&a.length>e.shortStringMaxLength&&(a=a.substring(0,e.shortStringMaxLength-3)+"...");if(e.escapeHtml){for(var q=a.split("\n"),l=0;l<q.length;l++)q[l]=dwr.util.escapeHtml(q[l]);a=q.join("\n")}a=0==b?a.replace(/\n|\r|\t/g,function(a){switch(a){case "\n":return"\\n";case "\r":return"";case "\t":return"\\t"}}):a.replace(/\n|\r|\t/g,function(a){switch(a){case "\n":return e.lineTerminator+f(c+1,e);case "\r":return"";
case "\t":return"\\t"}});g='"'+a+'"'}else if("function"==typeof a)g="function";else if(dwr.util._isArray(a))if(0==b)g=0<a.length?"[...]":"[]";else{var h=[];h.push("[");for(var m=0,l=0;l<a.length;l++)if(l in a){var t=a[l];0<m&&h.push(", ");if(1==b){if(m==e.oneLineMaxItems){h.push("...");break}}else h.push(e.lineTerminator+f(c+1,e));l!=m&&(h.push(l),h.push(":"));h.push(d(t,b-1,c+1,e));m++}1<b&&h.push(e.lineTerminator+f(c,e));h.push("]");g=h.join("")}else if(dwr.util._isObject(a)&&!dwr.util._isDate(a))if(0==
b)g=dwr.util._detailedTypeOf(a);else{h=[];"Object"!=dwr.util._detailedTypeOf(a)&&(h.push(dwr.util._detailedTypeOf(a)),"object"!=typeof a.valueOf()&&(h.push(":"),h.push(d(a.valueOf(),1,c,e))),h.push(" "));h.push("{");var u=dwr.util._isHTMLElement(a),m=0,n;for(n in a){var r=a[n];if(u){if(!r)continue;if("function"==typeof r)continue;if(p[n])continue;if(n.toUpperCase()==n)continue}0<m&&h.push(", ");if(1==b){if(m==e.oneLineMaxItems){h.push("...");break}}else h.push(e.lineTerminator+f(c+1,e));h.push(n.length>
e.propertyNameMaxLength?n.substring(0,e.propertyNameMaxLength-3)+"...":n);h.push(":");h.push(d(r,b-1,c+1,e));m++}1<b&&0<m&&h.push(e.lineTerminator+f(c,e));h.push("}");g=h.join("")}else g=""+a;return g}catch(s){return s.message?s.message:""+s}}function f(a,b){var c=[];c.push(b.baseIndent);for(var d=0;d<a;d++)c.push(b.childIndent);return c.join("")}void 0===b&&(b=1);var e={};dwr.util._isObject(c)&&(e=c);c={escapeHtml:!1,baseIndent:"",childIndent:"\u00a0\u00a0",lineTerminator:"\n",oneLineMaxItems:5,
shortStringMaxLength:13,propertyNameMaxLength:30};for(var g in c)g in e||(e[g]=c[g]);var p={document:!0,ownerDocument:!0,all:!0,parentElement:!0,parentNode:!0,offsetParent:!0,children:!0,firstChild:!0,lastChild:!0,previousSibling:!0,nextSibling:!0,innerHTML:!0,outerHTML:!0,innerText:!0,outerText:!0,textContent:!0,attributes:!0,style:!0,currentStyle:!0,runtimeStyle:!0,parentTextEdit:!0};return d(a,b,0,e)};
dwr.util.useLoadingMessage=function(a){var b;b=a?a:"Loading";dwr.engine.setPreHook(function(){var a=dwr.util.byId("disabledZone");if(a)dwr.util.byId("messageZone").innerHTML=b,a.style.visibility="visible",dwr.util._disabledZoneUseCount++,dwr.util.byId("messageZone").style.visibility="visible";else{a=document.createElement("div");a.setAttribute("id","disabledZone");a.style.position="absolute";a.style.zIndex="1000";a.style.left="0px";a.style.top="0px";a.style.width="100%";a.style.height="100%";window.ActiveXObject&&
(a.style.background="white",a.style.filter="alpha(opacity=0)");document.body.appendChild(a);a=document.createElement("div");a.setAttribute("id","messageZone");a.style.position="absolute";a.style.top="0px";a.style.right="0px";a.style.background="red";a.style.color="white";a.style.fontFamily="Arial,Helvetica,sans-serif";a.style.padding="4px";document.body.appendChild(a);var d=document.createTextNode(b);a.appendChild(d);dwr.util._disabledZoneUseCount=1}});dwr.engine.setPostHook(function(){dwr.util._disabledZoneUseCount--;
0==dwr.util._disabledZoneUseCount&&(dwr.util.byId("disabledZone").style.visibility="hidden",dwr.util.byId("messageZone").style.visibility="hidden")})};dwr.util.setHighlightHandler=function(a){dwr.util._highlightHandler=a};dwr.util.yellowFadeHighlightHandler=function(a){dwr.util._yellowFadeProcess(a,0)};dwr.util._yellowFadeSteps="d0 b0 a0 90 98 a0 a8 b0 b8 c0 c8 d0 d8 e0 e8 f0 f8".split(" ");
dwr.util._yellowFadeProcess=function(a,b){a=dwr.util.byId(a);b<dwr.util._yellowFadeSteps.length?(a.style.backgroundColor="#ffff"+dwr.util._yellowFadeSteps[b],setTimeout("dwr.util._yellowFadeProcess('"+a.id+"',"+(b+1)+")",200)):a.style.backgroundColor="transparent"};dwr.util.borderFadeHighlightHandler=function(a){a.style.borderWidth="2px";a.style.borderStyle="solid";dwr.util._borderFadeProcess(a,0)};dwr.util._borderFadeSteps="d0 b0 a0 90 98 a0 a8 b0 b8 c0 c8 d0 d8 e0 e8 f0 f8".split(" ");
dwr.util._borderFadeProcess=function(a,b){a=dwr.util.byId(a);b<dwr.util._borderFadeSteps.length?(a.style.borderColor="#ff"+dwr.util._borderFadeSteps[b]+dwr.util._borderFadeSteps[b],setTimeout("dwr.util._borderFadeProcess('"+a.id+"',"+(b+1)+")",200)):a.style.backgroundColor="transparent"};dwr.util.focusHighlightHandler=function(a){try{a.focus()}catch(b){}};dwr.util._highlightHandler=null;
dwr.util.highlight=function(a,b){b&&b.highlightHandler?b.highlightHandler(dwr.util.byId(a)):null!=dwr.util._highlightHandler&&dwr.util._highlightHandler(dwr.util.byId(a))};
dwr.util.setValue=function(a,b,c){null==b&&(b="");null==c&&(c={});var d=a;"string"==typeof a&&(a=dwr.util.byId(a))&&a.id!=d&&(a=null);var f=null;null==a&&(f=document.getElementsByName(d),1<=f.length&&(a=f.item(0)));if(null==a)dwr.util._debug("setValue() can't find an element with id/name: "+d+".");else if(dwr.util.highlight(a,c),dwr.util._isHTMLElement(a,"select"))"select-multiple"==a.type&&dwr.util._isArray(b)?dwr.util._selectListItems(a,b):dwr.util._selectListItem(a,b);else if(dwr.util._isHTMLElement(a,
"input"))if("radio"==a.type||"checkbox"==a.type)if(f&&1<=f.length)for(c=0;c<f.length;c++){if(d=f.item(c),d.type==a.type)if(dwr.util._isArray(b)){d.checked=!1;for(var e=0;e<b.length;e++)b[e]==d.value&&(d.checked=!0)}else d.checked=d.value==b}else a.checked=!0==b;else a.value=b;else dwr.util._isHTMLElement(a,"textarea")?a.value=b:dwr.util._isHTMLElement(a,"img")?a.src=b:b.nodeType?(9==b.nodeType&&(b=b.documentElement),b=dwr.util._importNode(a.ownerDocument,b,!0),a.appendChild(b)):dwr.util._shouldEscapeHtml(c)&&
"string"==typeof b?a.textContent?a.textContent=b:a.innerText?a.innerText=b:a.innerHTML=dwr.util.escapeHtml(b):a.innerHTML=b};dwr.util._selectListItems=function(a,b){var c,d;for(c=0;c<a.options.length;c++)for(a.options[c].selected=!1,d=0;d<b.length;d++)a.options[c].value==b[d]&&(a.options[c].selected=!0);for(c=0;c<a.options.length;c++)for(d=0;d<b.length;d++)a.options[c].text==b[d]&&(a.options[c].selected=!0)};
dwr.util._selectListItem=function(a,b){var c=!1,d;for(d=0;d<a.options.length;d++)a.options[d].value==b?c=a.options[d].selected=!0:a.options[d].selected=!1;if(!c)for(d=0;d<a.options.length;d++)a.options[d].selected=a.options[d].text==b};
dwr.util.getValue=function(a,b){null==b&&(b={});var c=a;"string"==typeof a&&(a=dwr.util.byId(a))&&a.id!=c&&(a=null);var d=null;null==a&&(d=document.getElementsByName(c),1<=d.length&&(a=d.item(0)));if(null==a)return dwr.util._debug("getValue() can't find an element with id/name: "+c+"."),"";if(dwr.util._isHTMLElement(a,"select")){if("select-multiple"==a.type){for(var c=[],f=0;f<a.options.length;f++)if(d=a.options[f],d.selected){var e=d.getAttributeNode("value");e&&e.specified?c.push(d.value):c.push(d.text)}return c}c=
a.selectedIndex;return-1!=c?(d=a.options[c],(e=d.getAttributeNode("value"))&&e.specified?d.value:d.text):""}if(dwr.util._isHTMLElement(a,"input")){if("radio"==a.type){if(d&&1<=d.length)for(f=0;f<d.length;f++)if(e=d.item(f),e.type==a.type&&e.checked)return e.value;return a.checked}if("checkbox"==a.type){if(d&&1<=d.length){c=[];for(f=0;f<d.length;f++)e=d.item(f),e.type==a.type&&e.checked&&c.push(e.value);return c}return a.checked}return"file"==a.type?a:a.value}if(dwr.util._isHTMLElement(a,"textarea"))return a.value;
if(dwr.util._shouldEscapeHtml(b)){if(a.textContent)return a.textContent;if(a.innerText)return a.innerText}return a.innerHTML};dwr.util.getText=function(a){a=dwr.util._getElementById(a,"getText()");if(null==a)return null;if(!dwr.util._isHTMLElement(a,"select"))return dwr.util._debug("getText() can only be used with select elements. Attempt to use: "+dwr.util._detailedTypeOf(a)+" from  id: "+orig+"."),"";var b=a.selectedIndex;return-1!=b?a.options[b].text:""};
dwr.util.setValues=function(a,b){var c="";b&&b.prefix&&(c=b.prefix);b&&b.idPrefix&&(c=b.idPrefix);dwr.util._setValuesRecursive(a,c)};
dwr.util._setValuesRecursive=function(a,b){if(dwr.util._isArray(a)&&0<a.length&&dwr.util._isObject(a[0]))for(var c=0;c<a.length;c++)dwr.util._setValuesRecursive(a[c],b+"["+c+"]");else if(dwr.util._isObject(a)&&!dwr.util._isArray(a))for(c in a){var d=b?b+"."+c:c;dwr.util._isObject(a[c])&&!dwr.util._isArray(a[c])||dwr.util._isArray(a[c])&&0<a[c].length&&dwr.util._isObject(a[c][0])?dwr.util._setValuesRecursive(a[c],d):"function"!=typeof a[c]&&(null!=dwr.util.byId(d)||1<=document.getElementsByName(d).length)&&
dwr.util.setValue(d,a[c])}};dwr.util.getValues=function(a,b){if("string"==typeof a||dwr.util._isHTMLElement(a))return dwr.util.getFormValues(a);var c="";null!=b&&b.prefix&&(c=b.prefix);null!=b&&b.idPrefix&&(c=b.idPrefix);dwr.util._getValuesRecursive(a,c);return a};
dwr.util.getFormValues=function(a){var b=null;"string"==typeof a?(b=document.forms[a],null==b&&(b=dwr.util.byId(a))):dwr.util._isHTMLElement(a)&&(b=a);if(null!=b){if(null==b.elements)return alert("getFormValues() requires an object or reference to a form element."),null;a={};for(var c,d,f=0;f<b.elements.length;f++)b[f].type in{button:0,submit:0,reset:0,image:0,file:0}||(b[f].name?(c=b[f].name,d=dwr.util.getValue(c)):(c=b[f].id?b[f].id:"element"+f,d=dwr.util.getValue(b[f])),a[c]=d);return a}};
dwr.util._getValuesRecursive=function(a,b){if(dwr.util._isArray(a)&&0<a.length&&dwr.util._isObject(a[0]))for(var c=0;c<a.length;c++)dwr.util._getValuesRecursive(a[c],b+"["+c+"]");else if(dwr.util._isObject(a)&&!dwr.util._isArray(a))for(c in a){var d=b?b+"."+c:c;dwr.util._isObject(a[c])&&!dwr.util._isArray(a[c])||dwr.util._isArray(a[c])&&0<a[c].length&&dwr.util._isObject(a[c][0])?dwr.util._getValuesRecursive(a[c],d):"function"!=typeof a[c]&&(null!=dwr.util.byId(d)||1<=document.getElementsByName(d).length)&&
(a[c]=dwr.util.getValue(d))}};
dwr.util.addOptions=function(a,b){a=dwr.util._getElementById(a,"addOptions()");if(null!=a){var c=dwr.util._isHTMLElement(a,"select"),d=dwr.util._isHTMLElement(a,["ul","ol"]);if(!c&&!d)dwr.util._debug("addOptions() can only be used with select/ul/ol elements. Attempt to use: "+dwr.util._detailedTypeOf(a));else if(null!=b){var f=arguments.length,e={},g=arguments[f-1];2<f&&dwr.util._isObject(g)&&(e=g,f--);g=null;3<=f&&(g=arguments[2]);var p=null;4<=f&&(p=arguments[3]);!e.optionCreator&&c&&(e.optionCreator=
dwr.util._defaultOptionCreator);!e.optionCreator&&d&&(e.optionCreator=dwr.util._defaultListItemCreator);if(dwr.util._isArray(b))for(var k=0;k<b.length;k++)if(e.data=b[k],e.text=null,e.value=null,c){if(null!=g?null!=p?(e.text=dwr.util._getValueFrom(b[k],p),e.value=dwr.util._getValueFrom(b[k],g)):e.text=e.value=dwr.util._getValueFrom(b[k],g):e.text=e.value=dwr.util._getValueFrom(b[k]),null!=e.text||e.value)d=e.optionCreator(e),d.text=e.text,d.value=e.value,a.options[a.options.length]=d}else e.value=
dwr.util._getValueFrom(b[k],g),null!=e.value&&(d=e.optionCreator(e),dwr.util._shouldEscapeHtml(e)&&(e.value=dwr.util.escapeHtml(e.value)),d.innerHTML=e.value,a.appendChild(d));else if(null!=p){if(!c){alert("dwr.util.addOptions can only create select lists from objects.");return}for(k in b)if(e.data=b[k],e.value=dwr.util._getValueFrom(b[k],g),e.text=dwr.util._getValueFrom(b[k],p),null!=e.text||e.value)d=e.optionCreator(e),d.text=e.text,d.value=e.value,a.options[a.options.length]=d}else{if(!c){dwr.util._debug("dwr.util.addOptions can only create select lists from objects.");
return}for(k in b)"function"!=typeof b[k]&&(e.data=b[k],g?(e.value=b[k],e.text=k):(e.value=k,e.text=b[k]),null!=e.text||e.value)&&(d=e.optionCreator(e),d.text=e.text,d.value=e.value,a.options[a.options.length]=d)}dwr.util.highlight(a,e)}}};dwr.util._getValueFrom=function(a,b){return null==b?a:"function"==typeof b?b(a):a[b]};dwr.util._defaultOptionCreator=function(a){return new Option};dwr.util._defaultListItemCreator=function(a){return document.createElement("li")};
dwr.util.removeAllOptions=function(a){a=dwr.util._getElementById(a,"removeAllOptions()");if(null!=a){var b=dwr.util._isHTMLElement(a,"select"),c=dwr.util._isHTMLElement(a,["ul","ol"]);if(b||c)if(b)a.options.length=0;else for(;0<a.childNodes.length;)a.removeChild(a.firstChild);else dwr.util._debug("removeAllOptions() can only be used with select, ol and ul elements. Attempt to use: "+dwr.util._detailedTypeOf(a))}};
dwr.util.addRows=function(a,b,c,d){a=dwr.util._getElementById(a,"addRows()");if(null!=a)if(dwr.util._isHTMLElement(a,["table","tbody","thead","tfoot"])){d||(d={});d.rowCreator||(d.rowCreator=dwr.util._defaultRowCreator);d.cellCreator||(d.cellCreator=dwr.util._defaultCellCreator);var f,e;if(dwr.util._isArray(b))for(e=0;e<b.length;e++)d.rowData=b[e],d.rowIndex=e,d.rowNum=e,d.data=null,d.cellNum=-1,f=dwr.util._addRowInner(c,d),null!=f&&a.appendChild(f);else if("object"==typeof b){e=0;for(var g in b)d.rowData=
b[g],d.rowIndex=g,d.rowNum=e,d.data=null,d.cellNum=-1,f=dwr.util._addRowInner(c,d),null!=f&&a.appendChild(f),e++}dwr.util.highlight(a,d)}else dwr.util._debug("addRows() can only be used with table, tbody, thead and tfoot elements. Attempt to use: "+dwr.util._detailedTypeOf(a))};
dwr.util._addRowInner=function(a,b){var c=b.rowCreator(b);if(null==c)return null;for(var d=0;d<a.length;d++){var f=a[d];b.data="function"==typeof f?f(b.rowData,b):f||"";b.cellNum=d;f=b.cellCreator(b);null!=f&&(null!=b.data&&(dwr.util._isHTMLElement(b.data)?f.appendChild(b.data):dwr.util._shouldEscapeHtml(b)&&"string"==typeof b.data?f.innerHTML=dwr.util.escapeHtml(b.data):f.innerHTML=b.data),c.appendChild(f))}return c};dwr.util._defaultRowCreator=function(a){return document.createElement("tr")};
dwr.util._defaultCellCreator=function(a){return document.createElement("td")};dwr.util.removeAllRows=function(a,b){a=dwr.util._getElementById(a,"removeAllRows()");if(null!=a)if(b||(b={}),b.filter||(b.filter=function(){return!0}),dwr.util._isHTMLElement(a,["table","tbody","thead","tfoot"]))for(var c=a.firstChild,d;null!=c;)d=c.nextSibling,b.filter(c)&&a.removeChild(c),c=d;else dwr.util._debug("removeAllRows() can only be used with table, tbody, thead and tfoot elements. Attempt to use: "+dwr.util._detailedTypeOf(a))};
dwr.util.setClassName=function(a,b){a=dwr.util._getElementById(a,"setClassName()");null!=a&&(a.className=b)};dwr.util.addClassName=function(a,b){a=dwr.util._getElementById(a,"addClassName()");null!=a&&(a.className+=" "+b)};dwr.util.removeClassName=function(a,b){a=dwr.util._getElementById(a,"removeClassName()");null!=a&&(a.className=a.className.replace(RegExp("(^|\\s)"+b+"(\\s|$)","g"),""))};
dwr.util.toggleClassName=function(a,b){a=dwr.util._getElementById(a,"toggleClassName()");if(null!=a){var c=RegExp("(^|\\s)"+b+"(\\s|$)");c.test(a.className)?a.className=a.className.replace(c,""):a.className+=" "+b}};dwr.util.cloneNode=function(a,b){a=dwr.util._getElementById(a,"cloneNode()");if(null==a)return null;null==b&&(b={});var c=a.cloneNode(!0);b.idPrefix||b.idSuffix?dwr.util._updateIds(c,b):dwr.util._removeIds(c);a.parentNode.insertBefore(c,a);return c};
dwr.util._updateIds=function(a,b){null==b&&(b={});a.id&&a.setAttribute("id",(b.idPrefix||"")+a.id+(b.idSuffix||""));for(var c=a.childNodes,d=0;d<c.length;d++){var f=c.item(d);1==f.nodeType&&dwr.util._updateIds(f,b)}};dwr.util._removeIds=function(a){a.id&&a.removeAttribute("id");a=a.childNodes;for(var b=0;b<a.length;b++){var c=a.item(b);1==c.nodeType&&dwr.util._removeIds(c)}};
dwr.util.cloneNodeForValues=function(a,b,c){a=dwr.util._getElementById(a,"cloneNodeForValues()");if(null==a)return null;null==c&&(c={});return dwr.util._cloneNodeForValuesRecursive(a,b,null!=c.idPrefix?c.idPrefix:a.id||"",c)};
dwr.util._cloneNodeForValuesRecursive=function(a,b,c,d){if(dwr.util._isArray(b)){for(var f=[],e=0;e<b.length;e++){var g=dwr.util._cloneNodeForValuesRecursive(a,b[e],c+"["+e+"]",d);f.push(g)}return f}if(dwr.util._isObject(b)&&!dwr.util._isArray(b)){g=a.cloneNode(!0);if(d.updateCloneStyle&&g.style)for(f in d.updateCloneStyle)g.style[f]=d.updateCloneStyle[f];dwr.util._replaceIds(g,a.id,c);a.parentNode.insertBefore(g,a);dwr.util._cloneSubArrays(b,c,d);return g}return null};
dwr.util._replaceIds=function(a,b,c){if(a.id){var d=null;if(a.id==b)d=c;else if(a.id.length>b.length&&a.id.substr(0,b.length)==b){var f=a.id.charAt(b.length);if("."==f||"["==f)d=c+a.id.substr(b.length)}d?a.setAttribute("id",d):a.removeAttribute("id")}a=a.childNodes;for(d=0;d<a.length;d++)f=a.item(d),1==f.nodeType&&dwr.util._replaceIds(f,b,c)};
dwr.util._cloneSubArrays=function(a,b,c){for(prop in a){var d=a[prop];if(dwr.util._isArray(d)){if(0<d.length&&dwr.util._isObject(d[0])){var f=b+"."+prop,e=dwr.util.byId(f);null!=e&&dwr.util._cloneNodeForValuesRecursive(e,d,f,c)}}else dwr.util._isObject(d)&&dwr.util._cloneSubArrays(d,b+"."+prop,c)}};dwr.util._getElementById=function(a,b){var c=a;a=dwr.util.byId(a);null==a&&dwr.util._debug(b+" can't find an element with id: "+c+".");return a};
dwr.util._isHTMLElement=function(a,b){if(null==a||"object"!=typeof a||null==a.nodeName)return!1;if(null!=b){var c=a.nodeName.toLowerCase();if("string"==typeof b)return c==b.toLowerCase();if(dwr.util._isArray(b)){for(var d=!1,f=0;f<b.length&&!d;f++)c==b[f].toLowerCase()&&(d=!0);return d}dwr.util._debug("dwr.util._isHTMLElement was passed test node name that is neither a string or array of strings");return!1}return!0};
dwr.util._detailedTypeOf=function(a){var b=typeof a;"object"==b&&(b=Object.prototype.toString.apply(a),b=b.substring(8,b.length-1));return b};dwr.util._isObject=function(a){return a&&"object"==typeof a};dwr.util._isArray=function(a){return a&&a.join};dwr.util._isDate=function(a){return a&&a.toUTCString?!0:!1};
dwr.util._importNode=function(a,b,c){var d;if(1==b.nodeType){d=a.createElement(b.nodeName);for(var f=0;f<b.attributes.length;f++){var e=b.attributes[f];null!=e.nodeValue&&""!=e.nodeValue&&d.setAttribute(e.name,e.nodeValue)}"undefined"!=typeof b.style&&(d.style.cssText=b.style.cssText)}else 3==b.nodeType&&(d=a.createTextNode(b.nodeValue));if(c&&b.hasChildNodes())for(f=0;f<b.childNodes.length;f++)d.appendChild(dwr.util._importNode(a,b.childNodes[f],!0));return d};
dwr.util._debug=function(a,b){var c=!1;try{window.console?(b&&window.console.trace&&window.console.trace(),window.console.log(a),c=!0):window.opera&&window.opera.postError&&(window.opera.postError(a),c=!0)}catch(d){}if(!c&&(c=document.getElementById("dwr-debug"))){var f=a+"<br/>"+c.innerHTML;2048<f.length&&(f=f.substring(0,2048));c.innerHTML=f}};
